### ISSUE TITLE
Cannot find type 'ClaySDK' in scope

### ISSUE THREAD

**Issue by robikovacs** [ClaySolutions/ClaySDKDemo#1]
Hello @jakov-clay !

We started working on our integration and followed all the steps in the readme, but we still get the following error:

![Screenshot 2022-03-28 at 12 13 24](https://user-images.githubusercontent.com/5718030/160366215-85529c19-45de-4cf6-973a-35d9230851da.png)

Note that `pod install` command was successful.

Best,
Robert from ROOM

**Comment by robikovacs** [comment]
Nver mind, I was using an older version of the Demo app. It works now with the latest version from Github.

**Comment by josoma03** [comment]
Hello @robikovacs !
How can I have `SaltoJustINMobileSDK.xcframework` copy?

**Comment by jakov-clay** [comment]
@josoma03 You need to contact our support, they will provide docs and access to that framework
